demo.yml data/weather update

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -29,7 +29,12 @@ jobs:
         run: |
           git config user.name "Github Actions"
           git config user.email "actions@users.noreply.github.com"
-          git add data/weather.db
-          git commit -m "Update sqlite db" && git push || true
+          if [ -f "data/weather.db" ]; then
+            git add data/weather.db
+            git commit -m "Update sqlite db"
+            git push || true
+          else
+            echo "weather.db not found, skipping commit"
+          fi
         
         
